---

#port: 4000
#host: 0.0.0.0
safe: true
source: /

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Cybersecurity in Robotics Workshop | IROS 2021"
keywords:    "Workshop, Tutorial, IROS, 2021, cybersecurity, robotics"
description: "IROS 2021 tutorial session for cybersecurity in robotics"
source_link: "https://github.com/cybersecurityrobotics/IROS2021"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  backdrop:  '#37474f'
  heavy_accent: '#616161'
  mid_accent: '#9e9e9e'

kramdown:
  auto_ids:  false
